#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

export venv=$OPENSHIFT_REPO_DIR/data/venv

if [ -d $venv ] ;
    echo "Not rebuilding virtualenv."
else
    virtualenv $venv
    source $venv/bin/activate

    pip install mdemos.server mdemos.menus mdemos.metrics
fi
