#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
nohup $OPENSHIFT_REPO_DIR/data/venv/bin/moksha-hub > $OPENSHIFT_HOMEDIR/diy/logs/server.log 2>&1 &
